from fpdf import FPDF
import config

class ValhallaiPDF(FPDF):
    def __init__(self, title_doc):
        super().__init__()
        self.title_doc = title_doc
        # On utilise les couleurs du thème "light" pour le PDF (plus propre à l'impression)
        self.colors = config.COLORS["light"]

    def header(self):
        # --- 1. DESSIN DU LOGO (DAMIER) ---
        # On recrée les 4 carrés du logo vectoriellement
        # Carré Haut-Gauche
        self.set_fill_color(r=41, g=90, b=99) # #295A63
        self.rect(x=10, y=10, w=4, h=4, style='F')
        # Carré Haut-Droite
        self.set_fill_color(r=200, g=169, b=81) # #C8A951
        self.rect(x=15, y=10, w=4, h=4, style='F')
        # Carré Bas-Gauche
        self.set_fill_color(r=26, g=60, b=66) # #1A3C42
        self.rect(x=10, y=15, w=4, h=4, style='F')
        # Carré Bas-Droite
        self.set_fill_color(r=230, g=213, b=167) # #E6D5A7
        self.rect(x=15, y=15, w=4, h=4, style='F')

        # --- 2. TITRE DE L'ENTREPRISE ---
        self.set_font('Helvetica', 'B', 16)
        self.set_xy(22, 11) # Position à droite du logo
        self.set_text_color(41, 90, 99) # Couleur Primary
        self.cell(0, 10, 'VALHALLAI', ln=0)
        
        # Sous-titre (Regulatory Shield)
        self.set_font('Helvetica', '', 8)
        self.set_xy(22, 16)
        self.set_text_color(100, 100, 100) # Gris
        self.cell(0, 5, 'REGULATORY SHIELD', ln=0)

        # --- 3. TITRE DU DOCUMENT (Variable) ---
        self.set_font('Helvetica', 'B', 12)
        self.set_xy(0, 12) # Alignement droite
        self.set_text_color(0, 0, 0)
        self.cell(190, 10, self.title_doc, align='R')

        # Ligne de séparation
        self.set_draw_color(200, 169, 81) # Couleur Accent (Gold)
        self.set_line_width(0.5)
        self.line(10, 22, 200, 22)
        self.ln(20) # Saut de ligne après l'header

    def footer(self):
        self.set_y(-15) # 1.5cm du bas
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128)
        
        # Ligne de séparation fine
        self.set_draw_color(200, 200, 200)
        self.line(10, 282, 200, 282)
        
        # Texte pied de page
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} - Generated by VALHALLAI Platform - Confidential', align='C')

    def add_content(self, text):
        self.add_page()
        self.set_font('Helvetica', '', 11)
        self.set_text_color(0)
        
        # Nettoyage basique du Markdown pour le PDF
        # (FPDF ne gère pas le gras **MD** nativement sans extension complexe)
        clean_text = text.replace('**', '').replace('### ', '').replace('## ', '')
        
        # Encodage latin-1 pour gérer les accents basiques si nécessaire, 
        # mais fpdf2 gère bien l'unicode par défaut si on utilisait une font ttf.
        # Ici on utilise la font standard Helvetica (rapide, pas de fichier à charger)
        # On force l'encodage pour éviter les crashs sur des emojis
        clean_text = clean_text.encode('latin-1', 'replace').decode('latin-1')

        self.multi_cell(0, 6, clean_text)

def generate_pdf_report(title, content):
    """Génère le PDF et retourne les bytes."""
    pdf = ValhallaiPDF(title)
    pdf.alias_nb_pages() # Pour le compteur de pages
    pdf.add_content(content)
    return pdf.output()
