from fpdf import FPDF
import config

class ValhallaiPDF(FPDF):
    def __init__(self, title_doc):
        super().__init__()
        self.title_doc = title_doc
        self.colors = config.COLORS["light"]

    def header(self):
        # Logo (Damier)
        self.set_fill_color(41, 90, 99) # Primary
        self.rect(10, 10, 4, 4, 'F')
        self.set_fill_color(200, 169, 81) # Accent
        self.rect(15, 10, 4, 4, 'F')
        self.set_fill_color(26, 60, 66) # Dark
        self.rect(10, 15, 4, 4, 'F')
        self.set_fill_color(230, 213, 167) # Light
        self.rect(15, 15, 4, 4, 'F')

        # Titre Entreprise
        self.set_font('Helvetica', 'B', 16)
        self.set_xy(22, 11)
        self.set_text_color(41, 90, 99)
        self.cell(0, 10, 'VALHALLAI', ln=0)
        
        # Sous-titre
        self.set_font('Helvetica', '', 8)
        self.set_xy(22, 16)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, 'REGULATORY SHIELD', ln=0)

        # Titre Document
        self.set_font('Helvetica', 'B', 12)
        self.set_xy(0, 12)
        self.set_text_color(0, 0, 0)
        self.cell(190, 10, self.title_doc, align='R')

        # Ligne séparation
        self.set_draw_color(200, 169, 81)
        self.set_line_width(0.5)
        self.line(10, 22, 200, 22)
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128)
        self.set_draw_color(200, 200, 200)
        self.line(10, 282, 200, 282)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} - Generated by VALHALLAI Platform - Confidential', align='C')

    def add_content(self, text):
        self.add_page()
        self.set_font('Helvetica', '', 11)
        self.set_text_color(0)
        # Nettoyage Markdown basique
        clean = text.replace('**', '').replace('### ', '').replace('## ', '')
        # Gestion encodage
        clean = clean.encode('latin-1', 'replace').decode('latin-1')
        self.multi_cell(0, 6, clean)

def generate_pdf_report(title, content):
    pdf = ValhallaiPDF(title)
    pdf.alias_nb_pages()
    pdf.add_content(content)
    # C'EST ICI LA CORRECTION IMPORTANTE : on force la conversion en bytes
    return bytes(pdf.output())
