import markdown
from xhtml2pdf import pisa
import io
from datetime import datetime

def generate_pdf_report(title, content_markdown, report_id):
    """
    Génère un PDF stylisé à partir de Markdown avec une mise en page aérée via CSS.
    Remplace FPDF pour un meilleur contrôle typographique (Line-height, margins).
    """
    
    # 1. Conversion du contenu Markdown en HTML
    html_content = markdown.markdown(content_markdown)

    # 2. Date du jour
    date_str = datetime.now().strftime("%d/%m/%Y")

    # 3. Template HTML avec CSS Avancé (C'est ici que se joue l'aération)
    html_template = f"""
    <html>
    <head>
        <style>
            @page {{
                size: A4;
                margin: 2.5cm;
                @frame footer_frame {{
                    -pdf-frame-content: footerContent;
                    bottom: 1cm;
                    margin-left: 2.5cm;
                    margin-right: 2.5cm;
                    height: 1cm;
                }}
            }}
            
            body {{
                font-family: Helvetica, sans-serif;
                font-size: 11pt;
                line-height: 1.6; /* CLIÉ : Augmente l'espace entre les lignes (Aération) */
                color: #333333;
            }}

            /* --- HEADER --- */
            .header-container {{
                padding-bottom: 20px;
                border-bottom: 2px solid #C8A951; /* Ligne dorée */
                margin-bottom: 30px;
            }}
            .brand {{
                color: #295A63;
                font-size: 20pt;
                font-weight: bold;
            }}
            .tagline {{
                color: #666;
                font-size: 9pt;
                letter-spacing: 2px;
                text-transform: uppercase;
            }}
            .meta-info {{
                text-align: right;
                font-size: 9pt;
                color: #888;
                margin-top: -35px; /* Remonte pour s'aligner avec le logo */
            }}

            /* --- TYPOGRAPHIE CONTENU --- */
            h1 {{
                color: #295A63;
                font-size: 22pt;
                margin-top: 0;
                margin-bottom: 20px;
            }}
            h2 {{
                color: #295A63;
                font-size: 16pt;
                margin-top: 25px;
                margin-bottom: 12px;
                border-bottom: 1px solid #eee;
                padding-bottom: 5px;
            }}
            h3 {{
                color: #1A3C42;
                font-size: 13pt;
                margin-top: 20px;
                margin-bottom: 10px;
                font-weight: bold;
            }}
            p {{
                margin-bottom: 15px; /* Espace sous chaque paragraphe */
                text-align: justify;
            }}
            
            /* --- LISTES (Le point critique) --- */
            ul, ol {{
                margin-top: 5px;
                margin-bottom: 20px;
                padding-left: 20px;
            }}
            li {{
                margin-bottom: 8px; /* AÉRATION : Espace entre chaque puce */
            }}

            /* --- FOOTER --- */
            #footerContent {{
                text-align: center;
                color: #aaa;
                font-size: 8pt;
                border-top: 1px solid #eee;
                padding-top: 10px;
            }}
            
            /* Highlight box pour les résumés */
            blockquote {{
                background-color: #f9f9f9;
                border-left: 5px solid #C8A951;
                padding: 10px 15px;
                margin: 20px 0;
                color: #555;
            }}
        </style>
    </head>
    <body>
        <div class="header-container">
            <div class="brand">VALHALLAI</div>
            <div class="tagline">Regulatory Shield</div>
            <div class="meta-info">
                <strong>{title}</strong><br/>
                Date: {date_str}
            </div>
        </div>

        {html_content}

        <div id="footerContent">
            Ref ID: {report_id} | Valhallai Platform Confidential | Generated by AI
        </div>
    </body>
    </html>
    """

    # 4. Génération du PDF binaire
    pdf_buffer = io.BytesIO()
    pisa_status = pisa.CreatePDF(
        io.StringIO(html_template),
        dest=pdf_buffer
    )

    if pisa_status.err:
        return None
    
    return pdf_buffer.getvalue()
